### PR TITLE
fix: revert PR-232

### PR DESCRIPTION
**Pull request by pritamstyz4ever**
## Context

Revert PR-232 [fix: fix for GIT_SHALLOW_CLONE and GIT_SHALLOW_CLONE_SINCE for fetch] because it is causing `git log` command returning only one line of log history (depth 1) and causing several builds which rely on tag from history to fail

## Objective

This PR removes the logic added for git fetch with --depth 1

## References

https://github.com/screwdriver-cd/scm-github/commit/f46b722aa2fdce4b1b0b32ce8cf13d753656cb83

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Review by VonnyJap — APPROVED** [review]

**Comment by yk634** [comment]
@pritamstyz4ever @VonnyJap 
I believe I have made the following modifications.

- If GIT_SHALLOW_CLONE is false, then fetching without depth will fetch all commits.
- Otherwise, by fetching with GIT_SHALLOW_CLONE_DEPTH_OPTION, the default is 50 depth, and if GIT_SHALLOW_CLONE_DEPTH or GIT_SHALLOW_CLONE_SINCE is set Fetch with that value.

Can you tell me in what builds you have had problems with depth=1?

**Comment by yk634** [comment]
Which version of the API is causing the problem?

The version reflecting https://github.com/screwdriver-cd/scm-github/pull/228 will be fetched with depth=1 and have only one commit.

I don't think this problem occurs in version [v7.5.0](https://github.com/screwdriver-cd/screwdriver/releases/tag/v7.0.150) or other versions that reflect https://github.com/screwdriver-cd/scm-github/pull/232.

**Comment by pritamstyz4ever** [comment]
`git log origin/master --format="%D"`
Expected result
```
grafted ..
tag v0.06


tag v0.05
tag v0.04

tag v0.02
```
Actual with the depth logic
```
grafted 
```
only one line returned
This command returns only one line of history for many of our builds, which relies on tags for further processing.
@yk634  can you check if GIT_SHALLOW_CLONE_DEPTH is replaced with correct options like `--depth=50`

**Comment by yk634** [comment]
@pritamstyz4ever 
I verified this with version [v7.0.148](https://github.com/screwdriver-cd/screwdriver/releases/tag/v7.0.148) before reflecting 　#232 and version [v7.0.157](https://github.com/screwdriver-cd/screwdriver/releases/tag/v7.0.157) after reflecting #232.
I ran `git log ${GIT_BRANCH} --format=“%D”` in each of the following cases, and multiple tags were successfully displayed.

- Builds triggered by commits to pipeline branches
  - GIT_SHALLOW_CLONE_SINGLE_BRANCH: false
  - GIT_SHALLOW_CLONE_SINGLE_BRANCH: true
  - GIT_SHALLOW_CLONE: false
- Build triggered by a tag created in the pipeline branch sha
  - GIT_SHALLOW_CLONE_SINGLE_BRANCH: false
  - GIT_SHALLOW_CLONE_SINGLE_BRANCH: true
  - GIT_SHALLOW_CLONE: false
- Build triggered by a tag created in the sha of a branch that is not a pipeline branch
  - GIT_SHALLOW_CLONE_SINGLE_BRANCH: false
  - GIT_SHALLOW_CLONE_SINGLE_BRANCH: true
    - v7.0.148 causes error in sd-setup-scm step.
    - In v7.0.157, git log command fails because no branches are fetched except pipeline branch.
  - GIT_SHALLOW_CLONE: false

In my verification, I have not found any problems with reflecting #232.
Can you give me more information about the build that is causing the problem, including environment variables and how it is triggered?

**Pull request merged**
