### PR TITLE
[3] Adding more information into the commit status

### PR DESCRIPTION
**Pull request by stjohnjohnson**
Adds a fun message and the job name (if passed).

Blocked by https://github.com/screwdriver-cd/scm-base/pull/7

### CODE REVIEW

**Comment by d2lam** [comment]
Build failed

**Comment by stjohnjohnson** [comment]
I don't get it, works locally.  What's with the error.

**Comment by d2lam** [comment]
@stjohnjohnson  It's because it was using node 4, I changed the wercker.yml. Build passed now.

**Comment by d2lam** [comment]
Just realized the `getId` [PR](https://app.wercker.com/Screwdriver/scm-github/runs/build/57e03dcdae73a70100524853?step=57e03dd23151e300011da9c6) from @catto was merged but never got deployed because it failed due to the same problem.

**Pull request merged**
