### PR TITLE
feat: Add support for --shallow-since

### PR DESCRIPTION
**Pull request by okorz001**
This PR exposes `--shallow-since` as `GIT_SHALLOW_CLONE_SINCE`. `GIT_SHALLOW_CLONE_SINCE` has priority over `GIT_SHALLOW_CLONE_DEPTH` but the default depth of 50 still works when `GIT_SHALLOW_CLONE_SINCE` is not defined. `GIT_SHALLOW_CLONE_SINCE` is quoted because it may contain spaces when used for relative dates, e.g. `8 weeks ago`.

I verified the shell command locally by temporarily setting `SD_GIT_WRAPPER` to `echo`.

Please let me know if there are additional changes that must be made to pass `GIT_SHALLOW_CLONE_SINCE` environment variable from from the pipeline yaml to the scm driver.

**Note:** It may be difficult to understand the shell fragment in isolation. The following diff shows the intended difference in the final shell command after indentation:
```diff
 if [ ! -z $GIT_SHALLOW_CLONE ] && [ $GIT_SHALLOW_CLONE = false ]; then \
     $SD_GIT_WRAPPER "git clone --recursive --quiet --progress --branch master $SCM_URL $SD_SOURCE_DIR"; \
 else \
-    if [ -z $GIT_SHALLOW_CLONE_DEPTH ]; then \
-        export GIT_SHALLOW_CLONE_DEPTH=50; \
+    if [ ! -z "$GIT_SHALLOW_CLONE_SINCE" ]; then \
+        export GIT_SHALLOW_CLONE_DEPTH_OPTION="--shallow-since='$GIT_SHALLOW_CLONE_SINCE'"; \
+    else \
+        if [ -z $GIT_SHALLOW_CLONE_DEPTH ]; then \
+            export GIT_SHALLOW_CLONE_DEPTH=50; \
+        fi; \
+        export GIT_SHALLOW_CLONE_DEPTH_OPTION="--depth=$GIT_SHALLOW_CLONE_DEPTH"; \
     fi; \
     export GIT_SHALLOW_CLONE_BRANCH="--no-single-branch"; \
     if [ "$GIT_SHALLOW_CLONE_SINGLE_BRANCH" = true ]; then \
         export GIT_SHALLOW_CLONE_BRANCH=""; \
     fi; \
-    $SD_GIT_WRAPPER "git clone --depth=$GIT_SHALLOW_CLONE_DEPTH $GIT_SHALLOW_CLONE_BRANCH --recursive --quiet --progress --branch master $SCM_URL $SD_SOURCE_DIR"; \
+    $SD_GIT_WRAPPER "git clone $GIT_SHALLOW_CLONE_DEPTH_OPTION $GIT_SHALLOW_CLONE_BRANCH --recursive --quiet --progress --branch master $SCM_URL $SD_SOURCE_DIR"; \
 fi && \
```

Related: screwdriver-cd/screwdriver#1641

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by okorz001** [comment]
I signed the CLA. (I am a Verizon Media employee.)

**Comment by jithin1987** [comment]
@okorz001 Thank you for your contribution 👍 
Could you also add this env  variable to our guide ? https://github.com/screwdriver-cd/guide
This section https://docs.screwdriver.cd/user-guide/environment-variables#user-configurable

**Comment by okorz001** [comment]
I opened a PR for the docs.

**Pull request merged**
