### PR TITLE
feat: use git command always via sd-step

### PR DESCRIPTION
**Pull request by sakka2**
changes to use git command always via sd-step.
this enables to run git command in images that git command does not exist.

### CODE REVIEW

**Comment by tk3fftk** [comment]
Related: https://github.com/screwdriver-cd/screwdriver/issues/479
This PR will resolve this issue.

**Comment by minz1027** [comment]
Can we not install the git pkg if it's already available in the image? It will take more time for the check out part to download the git pkg.

**Comment by FenrirUnbound** [comment]
> Can we not install the git pkg if it's already available in the image? It will take more time for the checkout part to download the git pkg.

I guess I don't know what you mean by "download the git package". If I'm understanding this PR correctly, it's leverage a shared step to perform the git operation.

If you're referring to "if the git binary isn't available, do a apt-get install git", then that's a hairy thing to do. You have to check which OS distribution the image is using, and then determine which package manager you need to leverage for installing the correct package.

**Comment by FenrirUnbound** [comment]
@sakka2 

I like it! Hopefully in the future, this whole checkout phase can be replaced by a single shared step so we no longer have a string of `command1 && command2 && command3....`.

**Comment by minz1027** [comment]
What I meant is: We should add a check before we do hab install.  If the `git` is available in the image then why shall we spend time to hap install it?

It's actually taking 44 seconds to install it.
https://cd.screwdriver.cd/pipelines/112/builds/5271
screen shot 2017-06-09 at 3 42 30 pm

**Comment by catto** [comment]
@minz1027 I agree with you that we should check if there is git command in a build container. I see habitat depot would be slow some times.
But setup-scm step is just one liner including `if`, so it would be complicated and hard to read and maintenance if we check the presence of the command.

**Comment by minz1027** [comment]
@catto Hmm, we should just check once in the very beginning right? BTW,
 why we need `sd-step exec core/git` in every single command? The first one should install the git pkg and then the rest can just use it like `git rest xxx` right?

**Comment by minz1027** [comment]
@catto Thanks for the detailed explanation! :) I really like the idea of having an option to `prepare` the pkg. Once we have that, we can modify the syntax here. But for now I think the PR is good to go. 👍

**Pull request merged**
