### PR TITLE
Add hookId to parseHook

### PR DESCRIPTION
**Pull request by minz1027**
Because of https://github.com/screwdriver-cd/data-schema/pull/81

### CODE REVIEW

**Comment by stjohnjohnson** [comment]
Description and labels please.  What min. data-schema do you need?

**Comment by stjohnjohnson** [comment]
`hookId` is now a required field.  If you were to rebuild right now it would break.  That's a backwards incompatible change without bumping major verison.  Please be **very** careful about making these changes.  If you want to slowly adopt a new field, use minor versions with optional fields.  That way you can update this PR to have min version of 14.1.x which supports that output.

**Comment by d2lam** [comment]
@stjohnjohnson  Yeah that's true. https://github.com/screwdriver-cd/data-schema/pull/81 should have been a major bump.

**Comment by minz1027** [comment]
@stjohnjohnson we are not using the parseHook any where now. But it makes sense to bump the data-scheme min version! 👍

**Comment by FenrirUnbound** [comment]
It's less about whether it's implemented. It's more about maintaining strong contracts, which is essentially what interface is exposed to the user and what input/output is defined by that interface.

**Comment by minz1027** [comment]
@FenrirUnbound fixed!

**Pull request merged**
