### PR TITLE
fix: export GIT_URL and GIT_BRANCH env variables

### PR DESCRIPTION
**Pull request by petey**
Context
=======
Exporting the branch and url like Jenkins does.

Objective
---------
For compatibility, this plugin should export `GIT_URL` and `GIT_BRANCH`. This is the only plugin that has direct access to the PR information.

Misc
-----
* Lint fixes.

### CODE REVIEW

**Comment by tkyi** [comment]
Should we also export the `GIT_COMMIT` (SHA that was checked out)?

**Comment by petey** [comment]
We *could* do that, but I don't know what the use case is for that. Is anyone asking for it? I think that information can also be fetched in the build with `git rev-parse HEAD`.

**Comment by tkyi** [comment]
No preference here.

We are also already making the SCM_URL available in the build I think: http://docs.screwdriver.cd/user-guide/environment-variables#source-code.

**Comment by petey** [comment]
We are, but it is missing the `.git` on the end. Normally this isn't important, but the specific case I'm adding this for needs it for some reason.

**Pull request merged**
